import type { AppState } from '@/types';

export const SEED_STATE: AppState = {
  version: 1,
  profile: {
    id: 'profile-1',
    name: 'Alex Rivera',
    title: 'Senior Product Engineer',
    email: 'alex.rivera@example.com',
    summary:
      'Full-stack engineer with 6 years of experience building product-led growth tools, internal platforms, and developer tooling. Passionate about making complex systems feel simple.',
    linkedinUrl: 'https://linkedin.com/in/alexrivera',
    avatarInitials: 'AR',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-09-01T10:00:00Z',
  },
  references: [
    {
      id: 'ref-1',
      token: 'tok-received-demo-1234',
      requesterProfileId: 'profile-1',
      refereeName: 'Sarah Chen',
      refereeEmail: 'sarah.chen@acme.com',
      refereeTitle: 'Engineering Manager',
      refereeCompany: 'Acme Corp',
      relationship: 'manager',
      contextNote:
        'Sarah managed me directly for 2 years on the Growth team at Acme Corp, overseeing my work on the onboarding redesign and platform migrations.',
      isTransferable: true,
      status: 'received',
      requestedAt: '2024-08-01T10:00:00Z',
      submittedAt: '2024-08-05T14:30:00Z',
      expiresAt: '2024-09-01T10:00:00Z',
      recommendation:
        "Alex is one of the most impactful engineers I've had the privilege of managing. Their ability to take ambiguous problems and turn them into clear, well-executed solutions is exceptional. During the onboarding redesign project, Alex led a cross-functional team and delivered a 34% improvement in activation rates — well ahead of schedule. Beyond their technical excellence, Alex brings a collaborative spirit and genuine empathy for users that elevates everyone around them. I would hire Alex again without hesitation.",
      ratings: {
        technical: 5,
        communication: 5,
        leadership: 4,
        teamwork: 5,
        overall: 5,
      },
      strengths: ['systems thinking', 'cross-functional leadership', 'user empathy', 'execution'],
      wouldHireAgain: true,
    },
    {
      id: 'ref-2',
      token: 'tok-pending-demo-5678',
      requesterProfileId: 'profile-1',
      refereeName: 'Marcus Johnson',
      refereeEmail: 'marcus@startupco.io',
      refereeTitle: 'CTO',
      refereeCompany: 'StartupCo',
      relationship: 'manager',
      contextNote:
        'Marcus was CTO at StartupCo where I worked as a founding engineer for 18 months.',
      isTransferable: false,
      status: 'pending',
      requestedAt: '2024-09-10T09:00:00Z',
      expiresAt: '2024-10-10T09:00:00Z',
    },
    {
      id: 'ref-3',
      token: 'tok-received-demo-9012',
      requesterProfileId: 'profile-1',
      refereeName: 'Priya Nair',
      refereeEmail: 'priya.nair@example.com',
      refereeTitle: 'Staff Engineer',
      refereeCompany: 'Acme Corp',
      relationship: 'peer',
      contextNote: 'Priya and I were peers on the Platform team at Acme Corp for 3 years.',
      isTransferable: true,
      status: 'received',
      requestedAt: '2024-07-15T10:00:00Z',
      submittedAt: '2024-07-20T11:00:00Z',
      expiresAt: '2024-08-15T10:00:00Z',
      recommendation:
        'Working alongside Alex has been one of the highlights of my career at Acme. Alex has a rare combination of deep technical skill and strong product intuition. They consistently asked the right questions, pushed back on scope creep, and found elegant solutions to gnarly infrastructure problems. Any team would be lucky to have Alex.',
      ratings: {
        technical: 5,
        communication: 4,
        leadership: 4,
        teamwork: 5,
        overall: 5,
      },
      strengths: ['technical depth', 'product instinct', 'mentorship'],
      wouldHireAgain: true,
    },
  ],
  achievements: [
    {
      id: 'ach-1',
      title: 'Onboarding Redesign — 34% activation lift',
      description:
        'Led end-to-end redesign of the user onboarding flow in collaboration with Design and PM. Conducted 12 user interviews, rebuilt the onboarding wizard in React, and A/B tested 3 variants.',
      impact: 'Increased new user activation rate by 34% (18% → 24%), adding ~$2.1M in ARR.',
      category: 'delivery',
      date: '2024-04-01',
      company: 'Acme Corp',
      role: 'Senior Product Engineer',
      tags: ['react', 'a/b testing', 'growth', 'user research'],
      createdAt: '2024-04-15T10:00:00Z',
      updatedAt: '2024-04-15T10:00:00Z',
    },
    {
      id: 'ach-2',
      title: 'Migrated monolith to microservices — 60% infra cost reduction',
      description:
        'Architected and led a 6-month migration of the core billing and auth services from a Rails monolith to independent Node.js microservices, coordinating across 4 engineering teams.',
      impact:
        'Reduced infrastructure costs by 60% and cut mean deployment time from 45min to 8min.',
      category: 'technical',
      date: '2023-11-01',
      company: 'Acme Corp',
      role: 'Senior Product Engineer',
      tags: ['architecture', 'microservices', 'node.js', 'devops'],
      createdAt: '2023-11-20T10:00:00Z',
      updatedAt: '2023-11-20T10:00:00Z',
    },
    {
      id: 'ach-3',
      title: 'Launched developer API — 200+ integrations in 6 months',
      description:
        'Designed and built the public REST API and developer documentation portal from scratch at StartupCo. Created SDK packages for Python, Node, and Ruby.',
      impact: '200+ third-party integrations within 6 months of launch, becoming a top growth lever.',
      category: 'technical',
      date: '2022-06-01',
      company: 'StartupCo',
      role: 'Founding Engineer',
      tags: ['api design', 'developer experience', 'sdk', 'documentation'],
      createdAt: '2022-07-01T10:00:00Z',
      updatedAt: '2022-07-01T10:00:00Z',
    },
    {
      id: 'ach-4',
      title: 'Engineering Excellence Award',
      description:
        'Recognized by the VP of Engineering for outstanding contributions to the platform reliability initiative and for leading the on-call rotation overhaul.',
      impact: 'Reduced on-call pages by 70% over 3 months by resolving systemic alert fatigue.',
      category: 'award',
      date: '2024-01-15',
      company: 'Acme Corp',
      role: 'Senior Product Engineer',
      tags: ['reliability', 'on-call', 'leadership'],
      createdAt: '2024-01-20T10:00:00Z',
      updatedAt: '2024-01-20T10:00:00Z',
    },
  ],
  career: [
    {
      id: 'career-1',
      company: 'Acme Corp',
      role: 'Senior Product Engineer',
      employmentType: 'full-time',
      startDate: '2022-09-01',
      isCurrent: true,
      location: 'San Francisco, CA',
      description:
        'Leading product engineering on the Growth team. Own the activation and onboarding surface, manage a direct report, and contribute to platform architecture decisions.',
      skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'AWS', 'Figma'],
      isPromotion: true,
      previousEntryId: 'career-2',
      createdAt: '2022-09-01T10:00:00Z',
      updatedAt: '2024-09-01T10:00:00Z',
    },
    {
      id: 'career-2',
      company: 'Acme Corp',
      role: 'Software Engineer II',
      employmentType: 'full-time',
      startDate: '2021-03-01',
      endDate: '2022-08-31',
      isCurrent: false,
      location: 'San Francisco, CA',
      description:
        'Joined as SWE II on the Platform team. Built internal tooling, improved CI/CD pipelines, and contributed to the microservices migration.',
      skills: ['TypeScript', 'React', 'Rails', 'PostgreSQL', 'Docker'],
      isPromotion: false,
      createdAt: '2021-03-01T10:00:00Z',
      updatedAt: '2022-09-01T10:00:00Z',
    },
    {
      id: 'career-3',
      company: 'StartupCo',
      role: 'Founding Engineer',
      employmentType: 'full-time',
      startDate: '2019-06-01',
      endDate: '2021-02-28',
      isCurrent: false,
      location: 'New York, NY',
      description:
        'Employee #4 at a developer tools startup. Built the core product from scratch — API, dashboard, billing — and grew the engineering team from 1 to 6.',
      skills: ['Node.js', 'React', 'Python', 'MongoDB', 'Stripe', 'Heroku'],
      isPromotion: false,
      createdAt: '2019-06-01T10:00:00Z',
      updatedAt: '2021-03-01T10:00:00Z',
    },
  ],
  activity: [
    {
      id: 'act-1',
      type: 'reference_received',
      title: 'Reference received from Sarah Chen',
      description: 'Engineering Manager at Acme Corp submitted a reference.',
      entityId: 'ref-1',
      createdAt: '2024-08-05T14:30:00Z',
    },
    {
      id: 'act-2',
      type: 'achievement_added',
      title: 'Achievement logged: Onboarding Redesign',
      description: '34% activation lift added to your achievements.',
      entityId: 'ach-1',
      createdAt: '2024-04-15T10:00:00Z',
    },
    {
      id: 'act-3',
      type: 'reference_requested',
      title: 'Reference requested from Marcus Johnson',
      description: 'Sent a reference request to CTO at StartupCo.',
      entityId: 'ref-2',
      createdAt: '2024-09-10T09:00:00Z',
    },
    {
      id: 'act-4',
      type: 'reference_received',
      title: 'Reference received from Priya Nair',
      description: 'Staff Engineer at Acme Corp submitted a reference.',
      entityId: 'ref-3',
      createdAt: '2024-07-20T11:00:00Z',
    },
    {
      id: 'act-5',
      type: 'achievement_added',
      title: 'Achievement logged: Engineering Excellence Award',
      description: 'Award added to your achievements.',
      entityId: 'ach-4',
      createdAt: '2024-01-20T10:00:00Z',
    },
    {
      id: 'act-6',
      type: 'career_entry_added',
      title: 'Promoted to Senior Product Engineer',
      description: 'Career milestone added at Acme Corp.',
      entityId: 'career-1',
      createdAt: '2022-09-01T10:00:00Z',
    },
  ],
};
