import type { AppState } from '@/types';

export const SEED_STATE: AppState = {
  version: 1,
  profile: {
    id: 'profile-1',
    name: 'Jordan Park',
    title: 'Senior Talent Acquisition Lead',
    email: 'jordan.park@meridiantech.com',
    summary:
      'Senior TA Lead with 7 years of experience in high-volume recruiting for mid-market tech and operations teams. Currently managing 40+ open roles at Meridian Tech, navigating a 3× spike in AI-generated application volume. Focused on finding verified, high-signal candidates — not just polished resumes.',
    linkedinUrl: 'https://linkedin.com/in/jordanpark',
    avatarInitials: 'JP',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  references: [
    {
      id: 'ref-1',
      token: 'tok-received-demo-1234',
      requesterProfileId: 'profile-1',
      refereeName: 'Sarah Chen',
      refereeEmail: 'sarah.chen@acme.com',
      refereeTitle: 'Engineering Manager',
      refereeCompany: 'Acme Corp',
      relationship: 'manager',
      contextNote:
        'Sarah managed Alex Rivera directly for 2 years on the Growth team at Acme Corp, overseeing their work on the onboarding redesign and platform migrations. Requesting this reference for an open Senior Engineer role (Req #AE-441).',
      isTransferable: true,
      status: 'received',
      requestedAt: '2024-08-01T10:00:00Z',
      submittedAt: '2024-08-04T14:30:00Z',
      expiresAt: '2025-08-01T10:00:00Z',
      recommendation:
        "Alex is one of the most impactful engineers I've had the privilege of managing. Their ability to take ambiguous problems and turn them into clear, well-executed solutions is exceptional. During the onboarding redesign project, Alex led a cross-functional team and delivered a 34% improvement in activation rates — well ahead of schedule. Beyond their technical excellence, Alex brings a collaborative spirit and genuine empathy for users that elevates everyone around them. I would hire Alex again without hesitation.",
      ratings: {
        technical: 5,
        communication: 5,
        leadership: 4,
        teamwork: 5,
        overall: 5,
      },
      strengths: ['systems thinking', 'cross-functional leadership', 'user empathy', 'execution'],
      wouldHireAgain: true,
      verificationStatus: 'verified',
      verificationDetails: {
        workEmailConfirmed: true,
        orgGraphMatch: true,
        ipVerified: true,
      },
      performancePredictorScore: 92,
    },
    {
      id: 'ref-2',
      token: 'tok-pending-demo-5678',
      requesterProfileId: 'profile-1',
      refereeName: 'Marcus Johnson',
      refereeEmail: 'marcus@startupco.io',
      refereeTitle: 'CTO',
      refereeCompany: 'StartupCo',
      relationship: 'manager',
      contextNote:
        'Marcus was CTO at StartupCo where Alex worked as a founding engineer for 18 months. Requesting for Req #AE-441 — his technical leadership perspective would be highly relevant.',
      isTransferable: false,
      status: 'pending',
      requestedAt: '2024-09-10T09:00:00Z',
      expiresAt: '2024-10-10T09:00:00Z',
      verificationStatus: 'unverified',
    },
    {
      id: 'ref-3',
      token: 'tok-received-demo-9012',
      requesterProfileId: 'profile-1',
      refereeName: 'Priya Nair',
      refereeEmail: 'priya.nair@acme.com',
      refereeTitle: 'Staff Engineer',
      refereeCompany: 'Acme Corp',
      relationship: 'peer',
      contextNote:
        'Priya and Alex were peers on the Platform team at Acme Corp for 3 years. This is a transferable reference — reusable across any hiring context.',
      isTransferable: true,
      status: 'received',
      requestedAt: '2024-07-15T10:00:00Z',
      submittedAt: '2024-07-18T11:00:00Z',
      expiresAt: '2025-07-15T10:00:00Z',
      recommendation:
        'Working alongside Alex has been one of the highlights of my career at Acme. Alex has a rare combination of deep technical skill and strong product intuition. They consistently asked the right questions, pushed back on scope creep, and found elegant solutions to gnarly infrastructure problems. Any team would be lucky to have Alex.',
      ratings: {
        technical: 5,
        communication: 4,
        leadership: 4,
        teamwork: 5,
        overall: 5,
      },
      strengths: ['technical depth', 'product instinct', 'mentorship'],
      wouldHireAgain: true,
      verificationStatus: 'verified',
      verificationDetails: {
        workEmailConfirmed: true,
        orgGraphMatch: true,
        ipVerified: true,
      },
      performancePredictorScore: 88,
    },
    {
      id: 'ref-4',
      token: 'tok-flagged-demo-3344',
      requesterProfileId: 'profile-1',
      refereeName: 'David Kim',
      refereeEmail: 'dkim.consultant@gmail.com',
      refereeTitle: 'VP Engineering',
      refereeCompany: 'NovaTech Solutions',
      relationship: 'manager',
      contextNote:
        'Candidate claims David was their VP for 3 years. Submitted reference for Req #PM-112.',
      isTransferable: false,
      status: 'received',
      requestedAt: '2024-09-01T09:00:00Z',
      submittedAt: '2024-09-02T10:00:00Z',
      expiresAt: '2025-09-01T09:00:00Z',
      recommendation:
        'This candidate performed well during their time with us. They were always on time and completed assigned work to a satisfactory standard. I would recommend them for a similar role.',
      ratings: {
        technical: 3,
        communication: 3,
        leadership: 3,
        teamwork: 3,
        overall: 3,
      },
      strengths: ['punctuality', 'reliability'],
      wouldHireAgain: false,
      verificationStatus: 'flagged',
      verificationDetails: {
        workEmailConfirmed: false,
        orgGraphMatch: false,
        ipVerified: false,
      },
      performancePredictorScore: 31,
    },
    {
      id: 'ref-5',
      token: 'tok-received-demo-5566',
      requesterProfileId: 'profile-1',
      refereeName: 'Rachel Torres',
      refereeEmail: 'r.torres@brightpath.com',
      refereeTitle: 'Director of Product',
      refereeCompany: 'BrightPath',
      relationship: 'manager',
      contextNote:
        'Rachel was Product Director at BrightPath where the candidate led growth initiatives for 2 years. Requesting for Req #PM-112.',
      isTransferable: true,
      status: 'received',
      requestedAt: '2024-08-20T10:00:00Z',
      submittedAt: '2024-08-22T15:00:00Z',
      expiresAt: '2025-08-20T10:00:00Z',
      recommendation:
        'Few PMs I have worked with match this candidate\'s ability to synthesize user feedback into sharp, actionable roadmap decisions. They drove a 28% improvement in our trial-to-paid conversion by rethinking our activation flow from scratch. They are unusually strong at navigating ambiguity and bringing engineering and design along without creating friction.',
      ratings: {
        technical: 4,
        communication: 5,
        leadership: 5,
        teamwork: 5,
        overall: 5,
      },
      strengths: ['roadmap strategy', 'stakeholder alignment', 'data-driven decisions', 'activation'],
      wouldHireAgain: true,
      verificationStatus: 'verified',
      verificationDetails: {
        workEmailConfirmed: true,
        orgGraphMatch: true,
        ipVerified: true,
      },
      performancePredictorScore: 91,
    },
  ],
  achievements: [
    {
      id: 'ach-1',
      title: 'Reduced time-to-hire by 38% on high-volume technical roles',
      description:
        'Redesigned the screening workflow for mid-level engineering roles by introducing structured reference captures at the shortlist stage instead of post-offer. Eliminated 2 rounds of redundant interviews.',
      impact:
        'Average time-to-hire dropped from 34 days to 21 days across 18 closed technical roles. Hiring manager satisfaction score increased from 6.2 to 8.7 / 10.',
      category: 'delivery',
      date: '2024-06-01',
      company: 'Meridian Tech',
      role: 'Senior TA Lead',
      tags: ['hiring velocity', 'process design', 'structured interviews', 'recruiter efficiency'],
      createdAt: '2024-06-20T10:00:00Z',
      updatedAt: '2024-06-20T10:00:00Z',
    },
    {
      id: 'ach-2',
      title: 'Caught 4 fraudulent reference submissions in Q3 2024',
      description:
        'Implemented a referee verification checklist (work email domain, LinkedIn tenure cross-check, IP anomaly flag) after a near-miss bad hire in Q2. Flagged 4 fraudulent references before offers were extended.',
      impact:
        'Avoided estimated $240K in bad-hire costs (onboarding + early attrition) based on internal cost-per-bad-hire model. Process is now standard across the TA team.',
      category: 'technical',
      date: '2024-09-30',
      company: 'Meridian Tech',
      role: 'Senior TA Lead',
      tags: ['fraud detection', 'risk management', 'reference verification', 'compliance'],
      createdAt: '2024-10-02T10:00:00Z',
      updatedAt: '2024-10-02T10:00:00Z',
    },
    {
      id: 'ach-3',
      title: 'Built reusable candidate reference passport pilot',
      description:
        'Piloted a "reference passport" model with 12 candidates where verified references were collected once and shared across multiple open roles. Candidates opted in; references were portable within a 12-month window.',
      impact:
        'Reduced reference re-collection effort by 65% for repeat candidates. Pilot candidates advanced to offer stage 22% faster than the control group.',
      category: 'growth',
      date: '2024-05-01',
      company: 'Meridian Tech',
      role: 'Senior TA Lead',
      tags: ['reference passport', 'reusable credentials', 'candidate experience', 'process innovation'],
      createdAt: '2024-05-15T10:00:00Z',
      updatedAt: '2024-05-15T10:00:00Z',
    },
    {
      id: 'ach-4',
      title: 'TA Innovator of the Year — North America (2023)',
      description:
        'Awarded by the HR Leadership Alliance for introducing predictive reference scoring at Meridian Tech, which correlated reference data with 6-month performance reviews across 30+ hires.',
      impact:
        'References scored 80+ on the predictor model showed a 2.1× lower early attrition rate vs. hires where references scored below 60.',
      category: 'award',
      date: '2023-11-15',
      company: 'Meridian Tech',
      role: 'Senior TA Lead',
      tags: ['predictive hiring', 'performance correlation', 'award', 'HR innovation'],
      createdAt: '2023-11-20T10:00:00Z',
      updatedAt: '2023-11-20T10:00:00Z',
    },
  ],
  career: [
    {
      id: 'career-1',
      company: 'Meridian Tech',
      role: 'Senior Talent Acquisition Lead',
      employmentType: 'full-time',
      startDate: '2022-03-01',
      isCurrent: true,
      location: 'Toronto, ON',
      description:
        'Leading end-to-end recruitment for 40+ open roles across Engineering, Product, and Operations. Managing a 3× spike in AI-generated applications while maintaining offer quality and reducing time-to-hire. Piloting structured reference intelligence tools to improve hiring signal.',
      skills: ['ATS (Greenhouse)', 'Structured Interviewing', 'Reference Verification', 'Sourcing', 'Data Analysis', 'LinkedIn Recruiter'],
      isPromotion: true,
      previousEntryId: 'career-2',
      createdAt: '2022-03-01T10:00:00Z',
      updatedAt: '2024-10-01T10:00:00Z',
    },
    {
      id: 'career-2',
      company: 'Meridian Tech',
      role: 'Talent Acquisition Specialist',
      employmentType: 'full-time',
      startDate: '2020-07-01',
      endDate: '2022-02-28',
      isCurrent: false,
      location: 'Toronto, ON',
      description:
        'Managed full-cycle recruiting for mid-level engineering and design roles. Introduced behavioral interviewing frameworks and reduced reliance on resume-only screening.',
      skills: ['ATS (Lever)', 'Behavioral Interviewing', 'Sourcing', 'Candidate Experience'],
      isPromotion: false,
      createdAt: '2020-07-01T10:00:00Z',
      updatedAt: '2022-03-01T10:00:00Z',
    },
    {
      id: 'career-3',
      company: 'TalentBridge Staffing',
      role: 'Recruiter',
      employmentType: 'full-time',
      startDate: '2018-02-01',
      endDate: '2020-06-30',
      isCurrent: false,
      location: 'Toronto, ON',
      description:
        'High-volume agency recruiting for contract and permanent placements in tech, finance, and operations. Closed 80+ placements per year with a 91% offer-acceptance rate.',
      skills: ['High-Volume Recruiting', 'Contract Staffing', 'Client Management', 'Boolean Search'],
      isPromotion: false,
      createdAt: '2018-02-01T10:00:00Z',
      updatedAt: '2020-07-01T10:00:00Z',
    },
  ],
  activity: [
    {
      id: 'act-1',
      type: 'reference_received',
      title: 'Reference received from Sarah Chen',
      description: 'Engineering Manager at Acme Corp submitted a verified reference for Req #AE-441.',
      entityId: 'ref-1',
      createdAt: '2024-08-04T14:30:00Z',
    },
    {
      id: 'act-2',
      type: 'reference_received',
      title: 'Fraud flag raised on David Kim reference',
      description: 'Work email unconfirmed, org-graph mismatch detected for Req #PM-112.',
      entityId: 'ref-4',
      createdAt: '2024-09-02T10:00:00Z',
    },
    {
      id: 'act-3',
      type: 'reference_requested',
      title: 'Reference requested from Marcus Johnson',
      description: 'Sent reference request to CTO at StartupCo for Req #AE-441.',
      entityId: 'ref-2',
      createdAt: '2024-09-10T09:00:00Z',
    },
    {
      id: 'act-4',
      type: 'reference_received',
      title: 'Reference received from Rachel Torres',
      description: 'Director of Product at BrightPath — Performance Predictor score: 91/100.',
      entityId: 'ref-5',
      createdAt: '2024-08-22T15:00:00Z',
    },
    {
      id: 'act-5',
      type: 'reference_received',
      title: 'Reference received from Priya Nair',
      description: 'Transferable reference from Staff Engineer at Acme Corp — reusable across roles.',
      entityId: 'ref-3',
      createdAt: '2024-07-18T11:00:00Z',
    },
    {
      id: 'act-6',
      type: 'achievement_added',
      title: 'Achievement logged: TA Innovator of the Year',
      description: 'Predictive reference scoring award added to achievements.',
      entityId: 'ach-4',
      createdAt: '2023-11-20T10:00:00Z',
    },
  ],
  // ─── Recruiter View: Candidates under review ─────────────────────────────
  candidateReviews: [
    {
      id: 'cand-1',
      candidateName: 'Alex Rivera',
      candidateEmail: 'alex.rivera@gmail.com',
      candidateCurrentTitle: 'Senior Product Engineer',
      appliedRole: 'Senior Software Engineer — Growth',
      reqNumber: 'AE-441',
      stage: 'reference_check',
      submittedAt: '2024-09-28T10:00:00Z',
      notes: 'Strong technical screen. Hiring manager loved the onboarding redesign story. References look clean.',
      references: [
        {
          id: 'csnap-1a',
          refereeName: 'Sarah Chen',
          refereeTitle: 'Engineering Manager',
          refereeCompany: 'Acme Corp',
          relationship: 'manager',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 92,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-10-01T14:00:00Z',
          recommendation: "Alex is one of the most impactful engineers I've managed. During the onboarding redesign, they led a cross-functional team and delivered a 34% improvement in activation ahead of schedule. I would hire them again without hesitation.",
          ratings: { technical: 5, communication: 5, leadership: 4, teamwork: 5, overall: 5 },
          strengths: ['systems thinking', 'cross-functional leadership', 'execution'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-1b',
          refereeName: 'Priya Nair',
          refereeTitle: 'Staff Engineer',
          refereeCompany: 'Acme Corp',
          relationship: 'peer',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 88,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-10-02T11:00:00Z',
          recommendation: 'Alex has a rare combination of deep technical skill and strong product intuition. They consistently asked the right questions and found elegant solutions to gnarly infrastructure problems.',
          ratings: { technical: 5, communication: 4, leadership: 4, teamwork: 5, overall: 5 },
          strengths: ['technical depth', 'product instinct', 'mentorship'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-1c',
          refereeName: 'Marcus Johnson',
          refereeTitle: 'CTO',
          refereeCompany: 'StartupCo',
          relationship: 'manager',
          verificationStatus: 'unverified',
          isTransferable: false,
          status: 'pending',
        },
      ],
    },
    {
      id: 'cand-2',
      candidateName: 'Taylor Brooks',
      candidateEmail: 'taylor.brooks@protonmail.com',
      candidateCurrentTitle: 'Product Manager',
      appliedRole: 'Senior Product Manager — Platform',
      reqNumber: 'PM-112',
      stage: 'reference_check',
      submittedAt: '2024-09-25T09:00:00Z',
      notes: 'David Kim reference flagged — work email unconfirmed and org-graph shows no record of employment at NovaTech. Recommend holding offer pending second reference.',
      references: [
        {
          id: 'csnap-2a',
          refereeName: 'Rachel Torres',
          refereeTitle: 'Director of Product',
          refereeCompany: 'BrightPath',
          relationship: 'manager',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 91,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-09-27T15:00:00Z',
          recommendation: "Taylor drove a 28% improvement in trial-to-paid conversion by rethinking our activation flow from scratch. Unusually strong at navigating ambiguity and bringing engineering and design along without friction.",
          ratings: { technical: 4, communication: 5, leadership: 5, teamwork: 5, overall: 5 },
          strengths: ['roadmap strategy', 'stakeholder alignment', 'data-driven decisions'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-2b',
          refereeName: 'David Kim',
          refereeTitle: 'VP Engineering',
          refereeCompany: 'NovaTech Solutions',
          relationship: 'manager',
          verificationStatus: 'flagged',
          verificationDetails: { workEmailConfirmed: false, orgGraphMatch: false, ipVerified: false },
          performancePredictorScore: 31,
          isTransferable: false,
          status: 'received',
          submittedAt: '2024-09-26T10:00:00Z',
          recommendation: 'Taylor performed well and was reliable. I would recommend them for a similar role.',
          ratings: { technical: 3, communication: 3, leadership: 3, teamwork: 3, overall: 3 },
          strengths: ['reliability'],
          wouldHireAgain: false,
        },
      ],
    },
    {
      id: 'cand-3',
      candidateName: 'Morgan Lee',
      candidateEmail: 'morgan.lee@email.com',
      candidateCurrentTitle: 'Engineering Lead',
      appliedRole: 'Staff Engineer — Infrastructure',
      reqNumber: 'ENG-209',
      stage: 'shortlisted',
      submittedAt: '2024-10-02T14:00:00Z',
      notes: 'Exceptional system design interview. Reference collection just started.',
      references: [
        {
          id: 'csnap-3a',
          refereeName: 'Danielle Wu',
          refereeTitle: 'VP Engineering',
          refereeCompany: 'Cloudscale',
          relationship: 'manager',
          verificationStatus: 'unverified',
          isTransferable: false,
          status: 'pending',
        },
        {
          id: 'csnap-3b',
          refereeName: 'Tariq Osman',
          refereeTitle: 'Principal Engineer',
          refereeCompany: 'Cloudscale',
          relationship: 'peer',
          verificationStatus: 'unverified',
          isTransferable: false,
          status: 'pending',
        },
      ],
    },
    {
      id: 'cand-4',
      candidateName: 'Simone Abara',
      candidateEmail: 'simone.abara@email.com',
      candidateCurrentTitle: 'Head of Growth',
      appliedRole: 'Director of Growth',
      reqNumber: 'GR-078',
      stage: 'offer',
      submittedAt: '2024-09-10T10:00:00Z',
      notes: 'All three references verified and strong. Offer approved. Proof Layer score: 94/100.',
      references: [
        {
          id: 'csnap-4a',
          refereeName: 'James Okafor',
          refereeTitle: 'CEO',
          refereeCompany: 'GrowthLoop',
          relationship: 'manager',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 96,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-09-14T09:00:00Z',
          recommendation: "Simone scaled our MRR from $800K to $3.2M in 18 months. She has an extraordinary intuition for channel mix and knows when to double down and when to cut. Best growth hire I've made.",
          ratings: { technical: 4, communication: 5, leadership: 5, teamwork: 5, overall: 5 },
          strengths: ['channel strategy', 'experimentation', 'team building', 'execution at scale'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-4b',
          refereeName: 'Claire Fontaine',
          refereeTitle: 'VP Marketing',
          refereeCompany: 'GrowthLoop',
          relationship: 'peer',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 93,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-09-15T11:00:00Z',
          recommendation: 'Simone is one of the most analytically rigorous growth leaders I have worked with. She built our experimentation framework from scratch and trained a team of 8.',
          ratings: { technical: 5, communication: 5, leadership: 4, teamwork: 5, overall: 5 },
          strengths: ['analytics', 'experimentation', 'people development'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-4c',
          refereeName: 'Ben Trask',
          refereeTitle: 'Board Member',
          refereeCompany: 'GrowthLoop',
          relationship: 'mentor',
          verificationStatus: 'verified',
          verificationDetails: { workEmailConfirmed: true, orgGraphMatch: true, ipVerified: true },
          performancePredictorScore: 94,
          isTransferable: true,
          status: 'received',
          submittedAt: '2024-09-16T14:00:00Z',
          recommendation: "Simone has the rare combination of strategic vision and operational discipline. She's the kind of leader who earns trust across the org instantly.",
          ratings: { technical: 4, communication: 5, leadership: 5, teamwork: 5, overall: 5 },
          strengths: ['strategic vision', 'trust-building', 'cross-functional leadership'],
          wouldHireAgain: true,
        },
      ],
    },
    {
      id: 'cand-5',
      candidateName: 'Devon Patel',
      candidateEmail: 'devon.p@email.com',
      candidateCurrentTitle: 'Frontend Engineer',
      appliedRole: 'Senior Software Engineer — Growth',
      reqNumber: 'AE-441',
      stage: 'rejected',
      submittedAt: '2024-09-20T09:00:00Z',
      notes: 'Rejected after reference check. Two of three referees were unverifiable and the written recommendations showed near-identical language, a known fraud signal.',
      references: [
        {
          id: 'csnap-5a',
          refereeName: 'Wei Zhang',
          refereeTitle: 'Engineering Manager',
          refereeCompany: 'TechCorp Inc.',
          relationship: 'manager',
          verificationStatus: 'flagged',
          verificationDetails: { workEmailConfirmed: false, orgGraphMatch: false, ipVerified: true },
          performancePredictorScore: 28,
          isTransferable: false,
          status: 'received',
          submittedAt: '2024-09-22T10:00:00Z',
          recommendation: 'Devon is a great engineer and always delivered on time. I would recommend Devon for any engineering role.',
          ratings: { technical: 4, communication: 4, leadership: 3, teamwork: 4, overall: 4 },
          strengths: ['delivery', 'reliability'],
          wouldHireAgain: true,
        },
        {
          id: 'csnap-5b',
          refereeName: 'Amy Chen',
          refereeTitle: 'Senior Engineer',
          refereeCompany: 'TechCorp Inc.',
          relationship: 'peer',
          verificationStatus: 'flagged',
          verificationDetails: { workEmailConfirmed: false, orgGraphMatch: false, ipVerified: false },
          performancePredictorScore: 24,
          isTransferable: false,
          status: 'received',
          submittedAt: '2024-09-22T11:00:00Z',
          recommendation: 'Devon is a great engineer and always delivered projects on time. I would recommend Devon for any engineering role.',
          ratings: { technical: 4, communication: 4, leadership: 3, teamwork: 4, overall: 4 },
          strengths: ['delivery', 'reliability'],
          wouldHireAgain: true,
        },
      ],
    },
  ],
};
